import type { ServiceDetail } from "@/components/service/ServiceTemplate";
import { PHOTOS } from "@/components/PhotoFrame";

export const SERVICE_DATA: Record<string, ServiceDetail> = {
  "outing-kantor": {
    slug: "outing-kantor",
    title: "Outing Kantor",
    titleEn: "Corporate Outing",
    short:
      "Retreat strategis untuk tim, dari 1 hingga 5 hari, dengan objective bisnis yang terukur.",
    description:
      "Outing kantor kami bukan paket wisata kantor biasa. Kami merancang program dengan narrative, agenda, dan logistik enterprise-grade yang mengukur dampak nyata ke engagement, alignment, dan culture activation tim Anda.",
    icon: "compass",
    duration: ["1 hari", "2D1N", "3D2N"],
    capacity: "50–800 pax",
    priceFrom: "IDR 750.000 / pax",
    heroPhoto: PHOTOS.outdoorTeam,
    bodyPhoto: PHOTOS.candid,
    outcomes: [
      "Team alignment yang dapat diukur via pre/post survey",
      "Engagement uplift rata-rata 27% (data 2025, sampel 47 program)",
      "Memorable experience yang dibahas berbulan-bulan internal",
      "Dokumentasi visual untuk employer branding & internal comms",
    ],
    who: [
      "HR Manager yang harus jalankan annual outing tahun ini",
      "GA Department yang butuh vendor enterprise-grade",
      "People & Culture yang fokus engagement & retention",
      "Direktur yang ingin moment alignment untuk regional team",
      "C-suite yang butuh strategic touchpoint dengan tim",
      "Procurement yang butuh transparan & compliance vendor",
    ],
    included: [
      "Strategic discovery & objective design",
      "Narrative & tema custom",
      "Itinerary day-by-day",
      "Venue sourcing & vetting",
      "Transportasi PP from Jakarta/Bandung",
      "Akomodasi enterprise-tier",
      "F&B 3x/hari + snack break",
      "Fasilitator bersertifikasi",
      "Dedicated Program Manager",
      "Medic on-site untuk grup 100+ pax",
      "Asuransi peserta IDR 1M",
      "Foto & video dokumentasi profesional",
      "Welcome kit & branded merchandise",
      "Post-event report dengan metrics",
    ],
    formats: [
      {
        label: "1 Day",
        description: "Day retreat dengan agenda kompak — recommended untuk grup 50–150 pax dengan budget controlled.",
        from: "IDR 750.000",
      },
      {
        label: "2D1N",
        description: "Standard format paling diminati. Cukup deep untuk meaningful, cukup ringkas untuk weekday-friendly.",
        from: "IDR 1.500.000",
      },
      {
        label: "3D2N",
        description: "Deep retreat untuk strategic alignment atau team reset. Recommended untuk leadership team.",
        from: "IDR 2.400.000",
      },
    ],
    tiers: [
      {
        name: "Essential",
        from: "IDR 750.000",
        description: "Untuk day program 50+ pax dengan agenda kompak dan venue standar.",
        features: [
          "Day program logistics",
          "Standard hotel/venue mid-tier",
          "Activities 3–4 sessions",
          "F&B lunch & snack",
          "Standard transportation",
          "Basic documentation",
        ],
      },
      {
        name: "Premium",
        from: "IDR 1.500.000",
        description: "Most popular. 2D1N dengan venue premium dan agenda yang lebih substantive.",
        features: [
          "2D1N full program",
          "Premium resort/villa",
          "Custom-designed activities",
          "Full F&B + welcome dinner",
          "Branded welcome kit",
          "Professional video recap",
          "Pre/post engagement survey",
          "Dedicated PM + Fasilitator",
        ],
      },
      {
        name: "Bespoke",
        from: "IDR 2.500.000",
        description: "Fully custom design untuk C-suite, board, atau program dengan complexity tinggi.",
        features: [
          "Full bespoke design",
          "Concierge-level logistics",
          "Exclusive venue option",
          "Premium F&B (chef's table option)",
          "Cinematic recap film",
          "Curated speaker/fasilitator",
          "Post-event coaching follow-up",
          "Executive aftercare",
        ],
      },
    ],
    faqs: [
      {
        q: "Berapa minimum peserta untuk outing kantor?",
        a: "Minimum 30 pax untuk program standar agar economy of scale tercapai. Untuk executive offsite dengan grup <30, kami tetap bisa handle dengan pricing tier Bespoke.",
      },
      {
        q: "Berapa lead time minimum yang disarankan?",
        a: "Untuk program 50–200 pax: minimum 6 minggu. Untuk 200+ pax: minimum 8 minggu. Untuk urgent (<4 minggu), kami punya rapid-response capability dengan surcharge.",
      },
      {
        q: "Apakah bisa multi-destinasi dalam 1 trip?",
        a: "Ya. Kami sering merancang program yang menggabungkan Bandung + Lembang, atau Bandung + Ciwidey. Untuk lintas-kota (Bandung + Jogja), butuh planning lebih panjang.",
      },
      {
        q: "Apakah ada paket dengan transportasi dari Jakarta?",
        a: "Ya, transportasi PP Jakarta–Bandung tersedia (bus eksekutif, mini bus, atau private car). Untuk grup besar, kami coordinate konvoi dengan jeda waktu agar arrival smooth.",
      },
      {
        q: "Bagaimana dengan peserta yang vegetarian atau alergi tertentu?",
        a: "Setiap pre-event briefing, kami collect dietary requirement detail. Catering kami support vegetarian, vegan, halal-certified, dan major allergies. Untuk requirement khusus, akan dikomunikasikan ke chef.",
      },
      {
        q: "Apa yang membedakan outing kantor kami dari vendor lain?",
        a: "Tiga hal: (1) Objective-driven design — bukan paket cookie-cutter, (2) Methodology 5-step yang terdokumentasi dan terukur, (3) Track record 13 tahun dengan 180+ enterprise client termasuk Fortune 500 Indonesia.",
      },
    ],
  },

  "team-building": {
    slug: "team-building",
    title: "Team Building",
    titleEn: "Team Building",
    short:
      "Aktivitas behavior-driven yang terikat dengan team OKR — bukan games random.",
    description:
      "Team building kami dirancang dari behavior team yang Anda ingin perkuat, bukan dari katalog aktivitas. Setiap exercise punya learning objective spesifik dan post-activity debrief yang dipimpin fasilitator bersertifikasi.",
    icon: "users",
    duration: ["Half-day", "Full-day", "2D1N"],
    capacity: "30–500 pax",
    priceFrom: "IDR 450.000 / pax",
    heroPhoto: PHOTOS.groupActivity,
    bodyPhoto: PHOTOS.activity1,
    outcomes: [
      "Behavior shift measurable via fasilitator debrief & survey",
      "Cross-functional understanding meningkat signifikan",
      "Action items konkret yang dibawa kembali ke kantor",
      "Kohesi tim yang berlanjut weeks/months post-event",
    ],
    who: [
      "HR L&D yang butuh program di luar workshop kelas",
      "Manager yang ingin breaking silos antar departemen",
      "Engineering Lead yang mau aktivasi cross-team",
      "People & Culture untuk new hire onboarding",
      "VP/Director untuk team kick-off awal tahun",
      "Project Lead pra mega-project launch",
    ],
    included: [
      "Diagnostic call: behavior gap analysis",
      "Custom activity design (3–8 modul)",
      "Sertifikasi fasilitator (Lencioni, DiSC, dll)",
      "Equipment & props lengkap",
      "Venue indoor/outdoor",
      "Pre/post behavior assessment",
      "Group debrief session terpimpin",
      "Personal reflection workbook",
      "Photo & video documentation",
      "Action plan template per team",
      "Post-event report kelompok",
      "30-day follow-up check-in",
    ],
    formats: [
      {
        label: "Half-day (3–4 jam)",
        description: "Tactical session focused untuk single behavior outcome. Cocok untuk integrate dengan agenda lain.",
        from: "IDR 450.000",
      },
      {
        label: "Full-day",
        description: "Comprehensive program dengan 4–6 modul + lunch & debrief. Format paling populer.",
        from: "IDR 850.000",
      },
      {
        label: "2D1N Intensive",
        description: "Deep immersion untuk team yang baru terbentuk atau menghadapi transformation period.",
        from: "IDR 1.800.000",
      },
    ],
    tiers: [
      {
        name: "Essential",
        from: "IDR 450.000",
        description: "Half-day program dengan 3–4 modul untuk objective tunggal.",
        features: [
          "Half-day program",
          "3–4 modul activity",
          "Junior fasilitator",
          "Equipment standar",
          "Basic debrief",
          "Lunch included",
        ],
      },
      {
        name: "Premium",
        from: "IDR 850.000",
        description: "Full-day dengan senior fasilitator dan pre/post assessment.",
        features: [
          "Full-day program",
          "Senior bersertifikasi fasilitator",
          "5–6 modul + customization",
          "Pre/post behavior assessment",
          "Group + individual debrief",
          "Action plan workbook",
          "Photo/video documentation",
        ],
      },
      {
        name: "Bespoke",
        from: "IDR 1.800.000",
        description: "Curriculum-grade program dengan psychometric assessment dan follow-up coaching.",
        features: [
          "2D1N intensive program",
          "Lead fasilitator + assistant",
          "Psychometric assessment (DiSC/CliftonStrengths)",
          "Custom modul untuk specific OKR",
          "Individual coaching session",
          "30 + 90 day follow-up",
          "Cinematic recap film",
          "Executive readout report",
        ],
      },
    ],
    faqs: [
      {
        q: "Apa perbedaan team building dan outbound?",
        a: "Outbound fokus ke physical adventure (rafting, paintball, dll). Team building fokus pada behavioral learning — aktivitas adalah vehicle, debrief adalah inti. Team building kami evidence-based dengan fasilitator bersertifikasi.",
      },
      {
        q: "Apa yang menjadi 'success metric' team building?",
        a: "Tiga metric: (1) Self-reported team cohesion uplift via survey, (2) Behavioral indicator yang diobservasi fasilitator, (3) Action item completion rate dalam 30-90 hari post-event.",
      },
      {
        q: "Apakah bisa dijalankan indoor di hotel/kantor?",
        a: "Sangat bisa. Banyak modul team building kami dirancang indoor-friendly untuk weekday session. Outdoor activity dijadikan opsional, bukan mandatory.",
      },
      {
        q: "Apakah ada modul khusus untuk leadership team?",
        a: "Ya. Kami punya curriculum khusus untuk C-suite & senior leadership: situational leadership, conflict resolution, strategic alignment, decision-making under uncertainty.",
      },
      {
        q: "Bagaimana untuk team remote / hybrid?",
        a: "Kami punya hybrid format: 1-day in-person intensive + 4-week async follow-up dengan tools digital. Cocok untuk team dengan members tersebar di multiple cities.",
      },
      {
        q: "Apa yang dilakukan fasilitator kami?",
        a: "Memimpin aktivitas, observasi behavior team, lead debrief session, surface insights yang tim sendiri mungkin tidak sadari, dan menyusun action plan. Senior fasilitator kami rata-rata 8+ tahun experience di L&D corporate.",
      },
    ],
  },

  "company-gathering": {
    slug: "company-gathering",
    title: "Company Gathering",
    titleEn: "Company Gathering",
    short:
      "Acara tahunan kelas enterprise — annual gathering, family day, town hall.",
    description:
      "Company gathering untuk 100–1.500 peserta dengan production-grade execution. Storytelling kuat, AV produksi konferensi, dan pengalaman yang membangun loyalitas brand internal jangka panjang.",
    icon: "stars",
    duration: ["1 hari", "2D1N"],
    capacity: "100–1500 pax",
    priceFrom: "IDR 850.000 / pax",
    heroPhoto: PHOTOS.gathering,
    bodyPhoto: PHOTOS.ceremonyWide,
    outcomes: [
      "Brand internal & company culture aktivasi nyata",
      "Mass logistics dijalankan dengan SOP enterprise",
      "Konten visual & video untuk employer branding tahunan",
      "Recognition moment yang memorable untuk top performers",
    ],
    who: [
      "HR Director untuk annual company gathering",
      "GA Department yang handle mass event 500+ pax",
      "Internal Comms untuk culture activation",
      "Founder/CEO yang ingin moment dengan whole company",
      "People Operations untuk family day & milestone celebration",
      "Brand/Marketing untuk internal brand campaign",
    ],
    included: [
      "Theme & narrative development",
      "Stage & AV production-grade",
      "MC profesional + talent booking",
      "Registration & check-in system",
      "Mass transportation coordination",
      "Catering 500–1500 pax",
      "Entertainment & live performance",
      "Award & recognition ceremony",
      "Photo booth + interactive area",
      "Family day games (jika applicable)",
      "Video recap cinematic",
      "Branded photo + merchandise",
      "Risk management & medic team",
      "Crowd control & security",
    ],
    formats: [
      {
        label: "Day Gathering",
        description: "Half-day to full-day event di venue convention/ballroom. 200–800 pax common.",
        from: "IDR 850.000",
      },
      {
        label: "2D1N Annual",
        description: "Annual gathering format dengan inap di resort. Memorable & substantive.",
        from: "IDR 1.700.000",
      },
      {
        label: "Family Day",
        description: "Untuk karyawan + keluarga. Aktivitas anak-anak, entertainment, photo session.",
        from: "IDR 950.000",
      },
    ],
    tiers: [
      {
        name: "Essential",
        from: "IDR 850.000",
        description: "Day gathering 200–500 pax dengan production standard.",
        features: [
          "Day event format",
          "Stage standard + sound system",
          "Lunch + snack catering",
          "MC + standard entertainment",
          "Basic AV production",
          "Photo documentation",
        ],
      },
      {
        name: "Premium",
        from: "IDR 1.700.000",
        description: "2D1N annual gathering dengan inap & full production.",
        features: [
          "2D1N format",
          "Premium resort accommodation",
          "Stage & AV conference-grade",
          "Headline entertainment talent",
          "Recognition ceremony",
          "Branded photo zone",
          "Cinematic video recap",
          "Welcome kit & merchandise",
        ],
      },
      {
        name: "Bespoke",
        from: "IDR 2.800.000",
        description: "Flagship annual event untuk 800–1500 pax dengan creative production.",
        features: [
          "Custom theme & narrative",
          "LED stage, theater-grade lighting",
          "Multi-camera live production",
          "Celebrity talent booking",
          "Custom set design",
          "Multi-zone activation",
          "On-site brand activation",
          "Annual report video output",
        ],
      },
    ],
    faqs: [
      {
        q: "Berapa kapasitas maksimum yang bisa kami handle?",
        a: "Kami pernah mengelola gathering hingga 1.500 pax dengan multi-venue arrangement. Untuk skala >1500, perlu planning extended 12+ minggu untuk venue, logistik, dan compliance.",
      },
      {
        q: "Apakah include booking artis/MC?",
        a: "Ya. Talent booking kami include — dari MC profesional, band, comedian, hingga celebrity headline. Tier Premium dan Bespoke include talent dengan fee yang sudah dikurasi sesuai budget.",
      },
      {
        q: "Bagaimana untuk family gathering dengan anak-anak?",
        a: "Kami punya format Family Day dengan kids zone tersupervisi, aktivitas usia 3–12 tahun, dietary kid-friendly, dan medic khusus pediatrik on-site.",
      },
      {
        q: "Apakah ada award ceremony module?",
        a: "Ya. Recognition ceremony adalah core module — kami design flow yang impactful dengan video tribute, trophy/plaque, dan moment yang quotable untuk internal comms.",
      },
      {
        q: "Bagaimana coordinate transportation untuk 1000+ pax?",
        a: "Kami punya SOP konvoi: staggered departure 30-menit window, multiple pickup points, dedicated coordinator per bus, real-time tracking, dan contingency vehicle backup.",
      },
      {
        q: "Apa yang dibuat untuk internal comms post-event?",
        a: "Standard delivery: highlight reel 60–90 detik, full event film 5–7 menit, kit foto curated, dan optional editable assets untuk internal newsletter / Instagram corporate.",
      },
    ],
  },

  "mice-bandung": {
    slug: "mice-bandung",
    title: "MICE Bandung",
    titleEn: "MICE",
    short:
      "Meeting, Incentive, Convention, Exhibition di Bandung dengan production-grade execution.",
    description:
      "Full-service MICE management — venue sourcing, AV production, registration, transportation, accommodation. Bandung adalah destinasi MICE strategis dengan akses Jakarta yang dekat, cuaca ideal sepanjang tahun, dan venue berkelas international.",
    icon: "presentation",
    duration: ["Day MICE", "Multi-day"],
    capacity: "50–2000 pax",
    priceFrom: "IDR 950.000 / pax",
    heroPhoto: PHOTOS.meeting,
    bodyPhoto: PHOTOS.banquet,
    outcomes: [
      "Production-grade execution: AV, lighting, stage international standard",
      "Vendor network preferred partner dengan negotiated rates",
      "Compliance & risk protocol enterprise",
      "Multi-day event managed end-to-end tanpa friction",
    ],
    who: [
      "Corporate Event Manager dengan budget enterprise",
      "Conference organizer untuk annual summit",
      "Sales Director untuk sales kick-off / SKO",
      "Marketing Lead untuk product launch event",
      "Association manager untuk industry conference",
      "Government / BUMN procurement untuk multi-stakeholder meeting",
    ],
    included: [
      "Venue sourcing & negotiation",
      "AV production: stage, sound, lighting",
      "Conference registration system",
      "Speaker management & green room",
      "Simultaneous interpretation (if needed)",
      "Multi-day catering coordination",
      "Coffee break & networking session",
      "Transportation: airport transfer + shuttle",
      "Accommodation block booking",
      "Welcome desk & signage",
      "Branded conference kit",
      "On-site PM team dedicated",
      "Live streaming option (optional)",
      "Post-event analytics report",
    ],
    formats: [
      {
        label: "Day MICE",
        description: "Single-day conference, meeting, atau corporate event di ballroom Bandung.",
        from: "IDR 950.000",
      },
      {
        label: "2-Day Conference",
        description: "Annual conference dengan multiple session tracks. Format paling umum.",
        from: "IDR 1.900.000",
      },
      {
        label: "3+ Day Convention",
        description: "Multi-day convention dengan exhibition. Butuh planning extended.",
        from: "IDR 2.800.000",
      },
    ],
    tiers: [
      {
        name: "Essential",
        from: "IDR 950.000",
        description: "Day MICE 100–300 pax dengan production standard.",
        features: [
          "Day event format",
          "Mid-tier ballroom venue",
          "Standard AV (basic stage, sound)",
          "Coffee break + lunch",
          "Registration desk",
          "Basic documentation",
        ],
      },
      {
        name: "Premium",
        from: "IDR 1.900.000",
        description: "2-day conference dengan production conference-grade.",
        features: [
          "2-day format",
          "Premium 5-star venue",
          "Stage + LED + lighting design",
          "Multi-camera capture",
          "Speaker coordination",
          "Networking session",
          "Accommodation block",
          "Branded conference kit",
        ],
      },
      {
        name: "Bespoke",
        from: "IDR 2.800.000",
        description: "Multi-day flagship convention dengan exhibition & customization.",
        features: [
          "3+ day format",
          "Exclusive venue arrangement",
          "Custom set & exhibition booth",
          "Multi-track session management",
          "International-grade production",
          "Live streaming + recording",
          "VIP hospitality lounge",
          "Real-time analytics dashboard",
        ],
      },
    ],
    faqs: [
      {
        q: "Mengapa Bandung untuk MICE?",
        a: "Tiga alasan strategis: (1) Akses dari Jakarta hanya 2.5 jam via Tol Cipularang, (2) Cuaca konsisten 20–25°C sepanjang tahun — ideal untuk venue indoor/outdoor mix, (3) Venue tier hotel international (Pullman, Marriott, Trans, Padma) dengan rate 30–40% lebih kompetitif dari Jakarta.",
      },
      {
        q: "Apa venue MICE Bandung yang sering dipakai?",
        a: "Top venue MICE Bandung: Trans Convention Center, Pullman Bandung Grand Central, The Trans Luxury Hotel, Sheraton Bandung, Marriott, Padma Bandung. Kami punya preferred partner agreement dengan most of them.",
      },
      {
        q: "Apakah include simultaneous interpretation?",
        a: "Ya, tersedia untuk conference dengan international speaker. ID-EN-Mandarin-Japanese paling sering kami coordinate. Equipment booth + interpreter bilingual disediakan partner kami.",
      },
      {
        q: "Bisakah handle MICE dengan exhibition booth?",
        a: "Sangat bisa. Kami coordinate booth design, fabrication, logistics, dan teardown. Untuk exhibition 30+ booth, kami assign dedicated exhibition coordinator.",
      },
      {
        q: "Bagaimana coordinate accommodation untuk peserta dari berbagai kota?",
        a: "Kami block-book hotel dengan group rate, design landing kit (welcome letter, transport info), dan provide dedicated check-in desk. Untuk peserta VIP, ada concierge handling.",
      },
      {
        q: "Apakah ada live streaming capability?",
        a: "Ya, kami partner dengan production house lokal. Multi-camera live streaming, dengan opsi simulcast ke YouTube, Zoom, atau platform internal. Recording master available untuk content repurposing.",
      },
    ],
  },

  "corporate-retreat": {
    slug: "corporate-retreat",
    title: "Corporate Retreat",
    titleEn: "Corporate Retreat",
    short:
      "Reflective retreat untuk leadership & senior team dengan setting alam Lembang/Ciwidey.",
    description:
      "Multi-day retreat yang dirancang untuk mendalami strategi, refleksi, dan alignment kepemimpinan. Setting alam yang tenang, agenda yang menyeimbangkan deep work dan recovery — sebuah pemutus dari rutinitas yang memungkinkan pemikiran strategis sesungguhnya.",
    icon: "mountain",
    duration: ["2D1N", "3D2N", "4D3N"],
    capacity: "10–80 pax",
    priceFrom: "IDR 2.400.000 / pax",
    heroPhoto: PHOTOS.retreat,
    bodyPhoto: PHOTOS.scenery,
    outcomes: [
      "Strategic clarity di level leadership — written commitments",
      "Personal & team alignment yang lebih dalam dari workshop biasa",
      "Output: roadmap & decision yang dieksekusi post-retreat",
      "Reset mental untuk leader yang menghadapi burnout risk",
    ],
    who: [
      "C-suite untuk annual strategic planning",
      "Board members untuk governance retreat",
      "Senior Leadership Team untuk alignment session",
      "Founder team di startup pasca-fundraising",
      "Partner di consulting/law/professional firm",
      "Senior management pasca-restructuring",
    ],
    included: [
      "Pre-retreat strategic interview (founder/CEO)",
      "Custom agenda design (strategy + reflection)",
      "Exclusive venue arrangement",
      "Senior fasilitator (strategist-grade)",
      "Optional: external speaker booking",
      "Premium accommodation (villa/boutique)",
      "Curated F&B (chef's table option)",
      "Wellness session (yoga/meditation optional)",
      "Quiet rooms / breakout spaces",
      "Note-taker & documentation team",
      "Strategic output document",
      "30 + 90 day follow-up call",
      "Concierge-level service",
      "Optional: spouse program (board retreat)",
    ],
    formats: [
      {
        label: "2D1N Strategic",
        description: "Focused offsite untuk single strategic theme — annual planning, transformation kick-off.",
        from: "IDR 2.400.000",
      },
      {
        label: "3D2N Deep",
        description: "Comprehensive retreat dengan ruang untuk strategy + personal + recovery. Most popular format.",
        from: "IDR 3.200.000",
      },
      {
        label: "4D3N Immersive",
        description: "Untuk leadership transformation atau board-level deep dive.",
        from: "IDR 4.500.000",
      },
    ],
    tiers: [
      {
        name: "Essential",
        from: "IDR 2.400.000",
        description: "2D1N untuk senior team dengan venue boutique tier.",
        features: [
          "2D1N format",
          "Boutique villa Lembang/Ciwidey",
          "Senior fasilitator",
          "Custom agenda",
          "Standard F&B",
          "Documentation",
        ],
      },
      {
        name: "Premium",
        from: "IDR 3.200.000",
        description: "3D2N retreat dengan venue exclusive dan wellness integration.",
        features: [
          "3D2N format",
          "Exclusive villa private",
          "Strategist + fasilitator",
          "Custom strategic agenda",
          "Curated F&B + wellness",
          "Pre-retreat 1:1 dengan CEO",
          "Strategic output document",
          "30 + 90 day follow-up",
        ],
      },
      {
        name: "Bespoke",
        from: "IDR 4.500.000",
        description: "Concierge-level retreat untuk C-suite & board.",
        features: [
          "Bespoke duration (custom)",
          "Ultra-private venue (eg. private vila + chef)",
          "Lead strategist + external speaker",
          "Custom-tailored agenda",
          "Premium concierge service",
          "Wellness team on-site",
          "Personal coach booking",
          "Quarterly follow-up program",
        ],
      },
    ],
    faqs: [
      {
        q: "Apa perbedaan corporate retreat dan corporate outing?",
        a: "Retreat fokus pada strategy + reflection (depth), outing fokus pada team experience (breadth). Retreat biasanya 6–80 pax dengan executive tier; outing 50–800 pax dengan broader participation.",
      },
      {
        q: "Apakah ada strategic fasilitator yang membantu sesi?",
        a: "Ya. Untuk retreat strategis, kami booking strategist-grade fasilitator (bukan generic outbound trainer). Mereka memandu strategic discussion, surface insights, dan structure output document.",
      },
      {
        q: "Apakah venue benar-benar exclusive?",
        a: "Untuk tier Premium dan Bespoke: ya, venue di-block exclusive (private villa/boutique resort). Tidak ada grup lain yang akan ada di venue saat program Anda berjalan.",
      },
      {
        q: "Apakah ada confidentiality agreement?",
        a: "Standar untuk retreat C-suite/board: NDA bilateral antara kami dan klien, plus NDA dengan setiap vendor on-site (kitchen, cleaning, dll). Confidentiality adalah operating norm.",
      },
      {
        q: "Apakah bisa include external speaker / coach?",
        a: "Ya, kami punya curated speaker bureau: business academic, ex-CEO, leadership coach. Sesuaikan dengan tema retreat — fee speaker terpisah dari paket.",
      },
      {
        q: "Apa output document yang dihasilkan?",
        a: "Tergantung kontrak: strategic roadmap, decision log, action commitments, atau internal whitepaper. Note-taker profesional akan capture, dan kami draft document untuk review CEO/lead.",
      },
    ],
  },

  "leadership-camp": {
    slug: "leadership-camp",
    title: "Leadership Camp",
    titleEn: "Leadership Development",
    short:
      "Curriculum-based leadership development immersion dengan kurikulum terstruktur.",
    description:
      "Program development pemimpin dengan curriculum-grade approach — modul tersusun, fasilitator bersertifikasi, framework yang diakui industri, dan pre/post assessment yang mengukur capability uplift.",
    icon: "flag",
    duration: ["3D2N", "5D4N"],
    capacity: "15–60 pax",
    priceFrom: "IDR 3.200.000 / pax",
    heroPhoto: PHOTOS.workshop,
    bodyPhoto: PHOTOS.pangalengan,
    outcomes: [
      "Capability uplift terukur dengan pre/post assessment",
      "Personal Development Plan (PDP) per peserta",
      "Cohort yang menjadi internal community jangka panjang",
      "Framework leadership yang konsisten across organization",
    ],
    who: [
      "L&D Manager dengan emerging leader pipeline",
      "HR Director untuk high-potential program",
      "Talent Management untuk succession planning",
      "Business Unit Head untuk middle management uplift",
      "Founder untuk founding team leadership growth",
      "Director untuk women-in-leadership cohort",
    ],
    included: [
      "Pre-program psychometric assessment",
      "Custom curriculum (5–8 modul)",
      "Lead fasilitator + ko-fasilitator",
      "External guest speaker (1–2)",
      "Action learning project per peserta",
      "1:1 coaching session (60 min)",
      "Peer feedback session terpimpin",
      "Personal Development Plan template",
      "Workbook & framework materials",
      "Cohort community platform (3 bulan)",
      "30, 60, 90-day follow-up check-in",
      "Manager debrief brief",
      "ROI measurement report",
      "Certificate of completion",
    ],
    formats: [
      {
        label: "3D2N Intensive",
        description: "Compact leadership camp untuk middle management. Fokus pada 1–2 core capability.",
        from: "IDR 3.200.000",
      },
      {
        label: "5D4N Deep",
        description: "Comprehensive leadership immersion untuk senior leader / high-potential cohort.",
        from: "IDR 5.800.000",
      },
      {
        label: "Modular (3 × 2D)",
        description: "Modular format — 3 sesi 2-hari spread over 3 bulan, dengan action learning di antaranya.",
        from: "IDR 6.500.000",
      },
    ],
    tiers: [
      {
        name: "Essential",
        from: "IDR 3.200.000",
        description: "3D2N camp untuk 15–30 emerging leader.",
        features: [
          "3D2N format",
          "Standard curriculum",
          "Bersertifikasi fasilitator",
          "Workbook + framework",
          "Group debrief",
          "Certificate",
        ],
      },
      {
        name: "Premium",
        from: "IDR 5.800.000",
        description: "5D4N immersion dengan psychometric + 1:1 coaching.",
        features: [
          "5D4N intensive",
          "Pre/post psychometric assessment",
          "Lead fasilitator + assistant",
          "Guest speaker (1)",
          "1:1 coaching session",
          "Action learning project",
          "30/60/90-day follow-up",
          "ROI measurement",
        ],
      },
      {
        name: "Bespoke",
        from: "IDR 8.500.000",
        description: "Custom curriculum + extended coaching engagement untuk strategic cohort.",
        features: [
          "Custom curriculum design",
          "Modular over 3–6 bulan",
          "Multiple guest speakers",
          "6 × 1:1 coaching sessions",
          "Sponsor/mentor matching",
          "Cohort community platform",
          "Sponsor executive readout",
          "Quarterly cohort reunion",
        ],
      },
    ],
    faqs: [
      {
        q: "Apa curriculum yang digunakan?",
        a: "Kami pakai framework yang diakui: Situational Leadership (Hersey-Blanchard), Growth Mindset (Dweck), Decision-Making (Heath Bros), Difficult Conversations (Stone et al.). Curriculum di-tailor sesuai brief tapi ground frameworknya tetap reputable.",
      },
      {
        q: "Apakah ada pre/post assessment?",
        a: "Ya. Standar tier Premium/Bespoke: pre-program psychometric (DiSC / Hogan / CliftonStrengths), post-program self-assessment + 360 feedback opsional, dan 90-day capability rating.",
      },
      {
        q: "Siapa fasilitator leadership camp kami?",
        a: "Bersertifikasi Coach (ICF/ACSTH), umumnya ex-corporate dengan 10+ tahun leadership experience. Untuk Bespoke, kami curate based on industry (banking expert untuk banking cohort, dll).",
      },
      {
        q: "Apakah include 1:1 coaching?",
        a: "Tier Premium: 1 session (60 min). Bespoke: 6 sessions over 3-6 bulan. Coaching dilakukan post-camp untuk solidify learning ke real situation.",
      },
      {
        q: "Berapa size cohort yang optimal?",
        a: "Sweet spot 18–24 peserta. Cukup besar untuk diverse interaction, cukup kecil untuk depth. Untuk cohort >30, kami split menjadi 2 cohort paralel atau sequential.",
      },
      {
        q: "Bagaimana measure ROI dari leadership camp?",
        a: "4 layer measurement: (1) Satisfaction post-event, (2) Learning gain (pre/post assessment), (3) Behavior change (90-day manager feedback), (4) Business impact (linked to KPI). Tier Premium include 1-3, Bespoke include semua.",
      },
    ],
  },

  "executive-offsite": {
    slug: "executive-offsite",
    title: "Executive Offsite",
    titleEn: "Executive Offsite",
    short:
      "Offsite strategis untuk C-suite dan board dengan concierge-level service.",
    description:
      "Offsite eksklusif untuk top leadership — fokus pada strategic planning, board alignment, dan decision-making di lingkungan yang memungkinkan deep thinking di luar tekanan operasional kantor.",
    icon: "briefcase",
    duration: ["2D1N", "3D2N"],
    capacity: "6–40 pax",
    priceFrom: "IDR 4.500.000 / pax",
    heroPhoto: PHOTOS.evening,
    bodyPhoto: PHOTOS.venueWide,
    outcomes: [
      "Strategic plan yang siap eksekusi dengan ownership clarity",
      "Confidential, high-trust setting untuk percakapan sulit",
      "Concierge-level service yang sesuai dengan executive expectation",
      "Reset moment yang melahirkan strategic insight sebenarnya",
    ],
    who: [
      "Board of Directors untuk governance retreat",
      "C-suite untuk annual strategic planning",
      "Founder team untuk product/strategy pivot",
      "Senior Partner di firm professional",
      "Family Office leadership",
      "Top 20 executive di multinational",
    ],
    included: [
      "Pre-offsite strategic interview",
      "Custom agenda dengan strategist input",
      "Ultra-private venue exclusive booking",
      "Lead strategist / facilitator",
      "Optional external thought leader speaker",
      "Concierge personal manager",
      "Premium catering (chef on-site)",
      "Wellness amenities curated",
      "Confidential note-taking & docs",
      "Discreet documentation team",
      "Strategic readout document",
      "Quarterly follow-up program",
      "NDA bilateral & vendor compliance",
      "VIP transportation arrangement",
    ],
    formats: [
      {
        label: "2D1N Strategic",
        description: "Fokus offsite untuk single strategic theme dengan executive depth.",
        from: "IDR 4.500.000",
      },
      {
        label: "3D2N Comprehensive",
        description: "Deep dive offsite dengan ruang untuk strategy + recovery + bonding.",
        from: "IDR 6.500.000",
      },
      {
        label: "Board Retreat (Tailored)",
        description: "Governance-level retreat dengan custom format. Discuss-based.",
        from: "IDR 8.500.000",
      },
    ],
    tiers: [
      {
        name: "Essential",
        from: "IDR 4.500.000",
        description: "2D1N untuk C-suite 6–15 pax dengan venue exclusive.",
        features: [
          "2D1N format",
          "Private boutique venue",
          "Senior fasilitator",
          "Strategic agenda",
          "Premium catering",
          "Confidential documentation",
        ],
      },
      {
        name: "Premium",
        from: "IDR 6.500.000",
        description: "3D2N dengan strategist + chef + concierge.",
        features: [
          "3D2N format",
          "Ultra-private villa",
          "Lead strategist + co-facilitator",
          "Pre-offsite 1:1 CEO interview",
          "Chef on-site experience",
          "Wellness program integrated",
          "Strategic readout document",
          "Quarterly follow-up",
        ],
      },
      {
        name: "Bespoke",
        from: "IDR 9.500.000",
        description: "Concierge-level board retreat dengan customization penuh.",
        features: [
          "Custom duration & venue",
          "International venue option",
          "External thought leader speaker",
          "Personal concierge per executive",
          "Bespoke chef tasting menu",
          "Wellness team (spa, meditation, fitness)",
          "Documentary-grade documentation",
          "1-year strategic partnership program",
        ],
      },
    ],
    faqs: [
      {
        q: "Apa yang membedakan executive offsite dari corporate retreat?",
        a: "Executive offsite lebih kecil (6–40 pax), lebih intensif strategically, lebih premium di execution, dan lebih confidential. Untuk board/C-suite — bukan untuk wider senior team.",
      },
      {
        q: "Bagaimana confidentiality protocol kami?",
        a: "Standar: NDA bilateral dengan klien, NDA dengan setiap vendor on-site (kitchen, cleaning, drivers), area off-limit untuk staff non-essential, no photo/video tanpa izin eksplisit, dan device check optional.",
      },
      {
        q: "Apakah ada strategist yang ikut memandu sesi?",
        a: "Ya. Untuk executive offsite, kami booking strategist-grade fasilitator — orang dengan background BCG/McKinsey/Bain alumni, atau ex-CEO/CFO yang familiar dengan executive dynamics.",
      },
      {
        q: "Bagaimana untuk requirement dietary executive yang sangat spesifik?",
        a: "Standar: chef on-site dengan kustomasi penuh. Dari ketogenic diet, vegan, allergen-free, hingga ritual-specific (halal kosher). Chef akan brief tasting menu sebelumnya untuk approval.",
      },
      {
        q: "Apakah bisa di venue internasional?",
        a: "Untuk tier Bespoke: ya. Kami bekerja dengan partner luxury travel network — Bali, Singapore, Vietnam, Australia. Lead time minimum 12 minggu untuk international.",
      },
      {
        q: "Apakah ada companion / spouse program?",
        a: "Untuk board retreat dengan spouse: optional companion program tersedia — curated experiences (cooking class, spa, museum tour) yang berjalan paralel dengan main agenda.",
      },
    ],
  },

  "incentive-trip": {
    slug: "incentive-trip",
    title: "Incentive Trip",
    titleEn: "Incentive Travel",
    short:
      "Rewards trip untuk top performer dan sales achiever, didesain dengan psikologi recognition.",
    description:
      "Trip apresiasi yang memorable untuk top performer. Premium experience yang menjadi motivator nyata untuk pencapaian target — desain trip berdasarkan psikologi recognition, bukan sekedar liburan mewah.",
    icon: "trophy",
    duration: ["2D1N", "3D2N"],
    capacity: "20–200 pax",
    priceFrom: "IDR 3.500.000 / pax",
    heroPhoto: PHOTOS.event,
    bodyPhoto: PHOTOS.ceremony,
    outcomes: [
      "Motivasi sales team meningkat (testable via leading indicator)",
      "Word-of-mouth internal yang kuat — drive aspirasi cohort berikutnya",
      "Linkage langsung ke commercial outcome bisnis",
      "Recognition moment yang quotable & employer branding asset",
    ],
    who: [
      "Sales Director untuk President's Club / Top Performer",
      "VP Sales untuk annual incentive program",
      "Channel Head untuk distributor reward",
      "Marketing Lead untuk agency incentive",
      "HR untuk milestone employee recognition",
      "Founder untuk early-team appreciation",
    ],
    included: [
      "Custom recognition program design",
      "Premium destination & venue",
      "Welcome ceremony & arrival ritual",
      "Curated experiences (unique to cohort)",
      "VIP transportation arrangement",
      "Branded recognition merchandise",
      "Award ceremony & trophy",
      "Premium F&B (chef's table option)",
      "Photographer & videographer dedicated",
      "Social-media-ready content kit",
      "Personalized welcome amenity",
      "Concierge per guest VIP",
      "Travel insurance premium",
      "Post-trip recap film",
    ],
    formats: [
      {
        label: "2D1N Domestic",
        description: "Reward trip dalam negeri (Bandung, Bali, Lombok) untuk cohort 30–100 pax.",
        from: "IDR 3.500.000",
      },
      {
        label: "3D2N Domestic",
        description: "Format paling populer — cukup substantif untuk feel memorable.",
        from: "IDR 5.500.000",
      },
      {
        label: "International (Tailored)",
        description: "Untuk top-tier achiever — Singapore, Bangkok, Bali luxury, Phuket.",
        from: "IDR 12.000.000",
      },
    ],
    tiers: [
      {
        name: "Essential",
        from: "IDR 3.500.000",
        description: "2D1N reward trip dengan recognition ceremony standar.",
        features: [
          "2D1N domestic",
          "Premium hotel 4★",
          "Award ceremony",
          "Group activity curated",
          "Standard F&B premium",
          "Photo + video recap",
        ],
      },
      {
        name: "Premium",
        from: "IDR 5.500.000",
        description: "3D2N dengan branded experience & concierge service.",
        features: [
          "3D2N domestic premium",
          "5★ resort/villa",
          "Custom recognition narrative",
          "Branded welcome experience",
          "VIP transportation",
          "Curated unique activity",
          "Dedicated photographer",
          "Cinematic recap film",
        ],
      },
      {
        name: "Bespoke",
        from: "IDR 12.000.000",
        description: "International luxury incentive untuk top-tier performer.",
        features: [
          "Domestic/international luxury",
          "Concierge per guest",
          "Chef-led culinary experience",
          "Exclusive VIP access (private tour, etc)",
          "Premium amenity kit",
          "Documentary-grade content team",
          "Personalized post-trip gift",
          "1-year achievement program ongoing",
        ],
      },
    ],
    faqs: [
      {
        q: "Bagaimana memilih destinasi yang tepat untuk incentive trip?",
        a: "Kami pakai 3 filter: (1) Aspirational level — apakah destinasi terasa premium dibanding standar lifestyle peserta, (2) Logistical feasibility — durasi, akses, dietary, (3) Story-ability — apakah destination 'quotable' untuk peer story setelah pulang.",
      },
      {
        q: "Apakah ada psikologi di balik design recognition?",
        a: "Ya. Kami menerapkan principle: surprise (unexpected moments), status (exclusive access), connection (peer-to-peer bonding), dan story (memorable narrative). Bukan sekedar 'liburan'.",
      },
      {
        q: "Apakah bisa international destination?",
        a: "Untuk tier Bespoke: ya. Singapore, Bangkok, Vietnam, Phuket adalah destinasi favorit untuk incentive premium. Lead time minimum 12 minggu (visa, logistics, premium booking).",
      },
      {
        q: "Berapa minimum cohort untuk incentive trip?",
        a: "Sweet spot 20–80 pax. Di bawah 20 — economy of scale terganggu. Di atas 80 — feeling exclusive berkurang. Untuk President's Club tier 1, kami rekomendasi cap di 30–50 untuk keep exclusivity tinggi.",
      },
      {
        q: "Bagaimana measure impact ke sales performance?",
        a: "Leading indicator: post-trip pulse survey (motivation, perceived recognition), peer aspiration data (% non-winner yang state 'will work to qualify next year'), dan commercial linkage (Q+1 vs Q-1 performance comparison).",
      },
      {
        q: "Apakah ada companion / spouse option?",
        a: "Common untuk tier President's Club: spouse program parallel atau combined. Tergantung culture company — kami flex sesuai brief.",
      },
    ],
  },
};
